//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivity
    {
        public tblActivity()
        {
            this.tblVarieties = new HashSet<tblVariety>();
        }
    
        public long activityId { get; set; }
        public string name { get; set; }
        public long locationId { get; set; }
        public long typeId { get; set; }
        public string description { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblMediumPrepType tblMediumPrepType { get; set; }
        public virtual ICollection<tblVariety> tblVarieties { get; set; }
    }
}
