//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventory
    {
        public long inventoryId { get; set; }
        public long reagentId { get; set; }
        public Nullable<int> quantity { get; set; }
        public string stock { get; set; }
        public Nullable<System.DateTime> stockDate { get; set; }
        public long stockUserId { get; set; }
        public Nullable<int> initialStock { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual tblReagent tblReagent { get; set; }
    }
}
