//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        public tblLocation()
        {
            this.tblActivities = new HashSet<tblActivity>();
            this.tblLocationUsers = new HashSet<tblLocationUser>();
        }
    
        public long locId { get; set; }
        public string name { get; set; }
        public string locNumber { get; set; }
        public string source { get; set; }
        public string description { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual ICollection<tblActivity> tblActivities { get; set; }
        public virtual ICollection<tblLocationUser> tblLocationUsers { get; set; }
    }
}
