//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMediumPrepType
    {
        public tblMediumPrepType()
        {
            this.tblActivities = new HashSet<tblActivity>();
        }
    
        public long typeId { get; set; }
        public string typename { get; set; }
    
        public virtual ICollection<tblActivity> tblActivities { get; set; }
    }
}
