//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartnerActivity
    {
        public long partnerActivityId { get; set; }
        public long partnerId { get; set; }
        public long reagentId { get; set; }
        public string backStopping { get; set; }
        public Nullable<int> tcPlantletsGiven { get; set; }
        public string bioreactorplantsGiven { get; set; }
        public string tubersGiven { get; set; }
        public string tcPlantletsAvailable { get; set; }
        public string tibPlantletsAvailable { get; set; }
        public string tubersAvailable { get; set; }
        public long officerInCharge { get; set; }
        public Nullable<System.DateTime> activityDate { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual tblReagent tblReagent { get; set; }
        public virtual tblPartner tblPartner { get; set; }
    }
}
