//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartner
    {
        public tblPartner()
        {
            this.tblPartnerActivities = new HashSet<tblPartnerActivity>();
            this.tblPartnerContacts = new HashSet<tblPartnerContact>();
        }
    
        public long partnerId { get; set; }
        public string name { get; set; }
        public string contactAddress { get; set; }
        public string phoneNumber { get; set; }
        public string emailAddress { get; set; }
        public string webAddress { get; set; }
        public Nullable<decimal> geoLongitude { get; set; }
        public Nullable<decimal> geoLatitude { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual ICollection<tblPartnerActivity> tblPartnerActivities { get; set; }
        public virtual ICollection<tblPartnerContact> tblPartnerContacts { get; set; }
    }
}
