//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReagent
    {
        public tblReagent()
        {
            this.tblInventories = new HashSet<tblInventory>();
            this.tblPartnerActivities = new HashSet<tblPartnerActivity>();
        }
    
        public long reagentId { get; set; }
        public string name { get; set; }
        public string uom { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> craetedDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual ICollection<tblInventory> tblInventories { get; set; }
        public virtual ICollection<tblPartnerActivity> tblPartnerActivities { get; set; }
    }
}
