//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVarietyProcessFlow
    {
        public long proccessId { get; set; }
        public long varietyId { get; set; }
        public string form { get; set; }
        public Nullable<System.DateTime> processDate { get; set; }
        public long userId { get; set; }
        public string rank { get; set; }
        public string barcode { get; set; }
        public string description { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual tblVariety tblVariety { get; set; }
    }
}
