//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVariety
    {
        public tblVariety()
        {
            this.tblVarietyProcessFlows = new HashSet<tblVarietyProcessFlow>();
        }
    
        public long varietyId { get; set; }
        public string name { get; set; }
        public string sampleNumber { get; set; }
        public int repUser { get; set; }
        public Nullable<System.DateTime> testDate { get; set; }
        public string releaseStatus { get; set; }
        public string resistance { get; set; }
        public string storability { get; set; }
        public string poundability { get; set; }
        public string species { get; set; }
        public string uniformity { get; set; }
        public string stability { get; set; }
        public string distinctness { get; set; }
        public Nullable<long> value { get; set; }
        public long activityId { get; set; }
        public long locationId { get; set; }
        public long userId { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual tblActivity tblActivity { get; set; }
        public virtual ICollection<tblVarietyProcessFlow> tblVarietyProcessFlows { get; set; }
    }
}
