//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamHighRatioSys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CropBreedingUnitDBEntities : DbContext
    {
        public CropBreedingUnitDBEntities()
            : base("name=CropBreedingUnitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblActivity> tblActivities { get; set; }
        public virtual DbSet<tblInventory> tblInventories { get; set; }
        public virtual DbSet<tblLocation> tblLocations { get; set; }
        public virtual DbSet<tblLocationUser> tblLocationUsers { get; set; }
        public virtual DbSet<tblMediumPrepType> tblMediumPrepTypes { get; set; }
        public virtual DbSet<tblPartner> tblPartners { get; set; }
        public virtual DbSet<tblPartnerActivity> tblPartnerActivities { get; set; }
        public virtual DbSet<tblPartnerContact> tblPartnerContacts { get; set; }
        public virtual DbSet<tblReagent> tblReagents { get; set; }
        public virtual DbSet<tblVariety> tblVarieties { get; set; }
        public virtual DbSet<tblVarietyProcessFlow> tblVarietyProcessFlows { get; set; }
    }
}
